-- Preserve existing rows; legacy documents require classification review and scanning.
CREATE TABLE IF NOT EXISTS operation_locks (id text PRIMARY KEY);
INSERT INTO operation_locks(id) VALUES ('business'),('security'),('uploads') ON CONFLICT DO NOTHING;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS classification text NOT NULL DEFAULT 'restricted' CHECK(classification IN ('internal','financial','network','restricted'));
ALTER TABLE documents ADD COLUMN IF NOT EXISTS scan_status text NOT NULL DEFAULT 'pending' CHECK(scan_status IN ('pending','clean','infected','error'));
ALTER TABLE documents ADD COLUMN IF NOT EXISTS sha256 text;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS scan_error text;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS scanned_at timestamptz;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS deleted_at timestamptz;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS purged_at timestamptz;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS classification text NOT NULL DEFAULT 'restricted' CHECK(classification IN ('internal','financial','network','restricted'));
ALTER TABLE reports ADD COLUMN IF NOT EXISTS audience text NOT NULL DEFAULT 'internal' CHECK(audience IN ('internal','customer'));
ALTER TABLE reports ADD COLUMN IF NOT EXISTS issue_reason text NOT NULL DEFAULT '';
ALTER TABLE reports ADD COLUMN IF NOT EXISTS document_number text;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS withdrawn_at timestamptz;
ALTER TABLE entries ADD COLUMN IF NOT EXISTS customer_visible boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS must_change_password boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS privacy_erased_at timestamptz;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS privacy_erased_at timestamptz;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS last_seen_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS client_address text NOT NULL DEFAULT 'unknown';
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS user_agent text NOT NULL DEFAULT '';
ALTER TABLE job_runs ADD COLUMN IF NOT EXISTS heartbeat_at timestamptz;
ALTER TABLE job_runs ADD COLUMN IF NOT EXISTS started_at timestamptz;
ALTER TABLE job_runs ADD COLUMN IF NOT EXISTS last_duration_ms integer;
ALTER TABLE import_batches ADD COLUMN IF NOT EXISTS summary jsonb NOT NULL DEFAULT '{}';
CREATE TABLE IF NOT EXISTS download_grants (id text PRIMARY KEY,user_id text NOT NULL REFERENCES users(id),document_id text NOT NULL REFERENCES documents(id),reason text NOT NULL,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS security_logs (sequence bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,id text NOT NULL UNIQUE,user_id text,action text NOT NULL,resource_kind text NOT NULL,resource_ids jsonb NOT NULL DEFAULT '[]',outcome text NOT NULL,client_address text NOT NULL,request_id text NOT NULL,reason text NOT NULL DEFAULT '',occurred_at timestamptz NOT NULL,previous_hash text NOT NULL,signature text NOT NULL,mirrored_at timestamptz);
CREATE TABLE IF NOT EXISTS privacy_policies (resource_kind text PRIMARY KEY,purpose text NOT NULL DEFAULT '',lawful_basis text NOT NULL DEFAULT '',retention_days integer CHECK(retention_days BETWEEN 1 AND 36500),retention_start text NOT NULL DEFAULT 'archived_at',exception_rule text NOT NULL DEFAULT '',approved_by text REFERENCES users(id),approved_at timestamptz,version integer NOT NULL DEFAULT 1);
INSERT INTO privacy_policies(resource_kind) VALUES ('customers'),('users'),('documents'),('reports'),('business_history'),('security_logs'),('backups') ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS privacy_holds (id text PRIMARY KEY,subject_kind text NOT NULL CHECK(subject_kind IN ('customers','users')),subject_id text NOT NULL,reason text NOT NULL,authority text NOT NULL,active boolean NOT NULL DEFAULT true,created_by text NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS privacy_requests (id text PRIMARY KEY,subject_kind text NOT NULL CHECK(subject_kind IN ('customers','users')),subject_id text NOT NULL,reason text NOT NULL,lawful_basis text NOT NULL,state text NOT NULL DEFAULT 'preview' CHECK(state IN ('preview','pending_files','pending_backups','completed','cancelled')),inventory jsonb NOT NULL,inventory_hash text NOT NULL,created_by text NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL,executed_at timestamptz,backup_disposition text,backup_confirmed_at timestamptz);
CREATE TABLE IF NOT EXISTS privacy_tombstones (id text PRIMARY KEY,subject_kind text NOT NULL,subject_id text NOT NULL,erased_at timestamptz NOT NULL DEFAULT now(),request_id text NOT NULL);
CREATE TABLE IF NOT EXISTS backup_runs (id text PRIMARY KEY,status text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,expires_at timestamptz,encrypted boolean NOT NULL DEFAULT true,manifest_hash text,error_code text);
CREATE TABLE IF NOT EXISTS security_reviews (id text PRIMARY KEY,reviewer_id text NOT NULL REFERENCES users(id),from_date date NOT NULL,to_date date NOT NULL,findings text NOT NULL,follow_up text NOT NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS documents_entity_acl_idx ON documents(entity_kind,entity_id,classification,created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS documents_scan_idx ON documents(scan_status,created_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS reports_entity_acl_idx ON reports(entity_kind,entity_id,classification,created_at DESC) WHERE withdrawn_at IS NULL;
CREATE INDEX IF NOT EXISTS security_logs_time_idx ON security_logs(occurred_at,user_id);
CREATE INDEX IF NOT EXISTS sessions_user_idx ON sessions(user_id,last_seen_at);
CREATE INDEX IF NOT EXISTS plans_asset_idx ON maintenance_plans(asset_id,status);
CREATE INDEX IF NOT EXISTS inspections_asset_idx ON inspections(asset_id,planned_date);
CREATE INDEX IF NOT EXISTS tickets_customer_idx ON tickets(customer_id,created_at DESC);
CREATE INDEX IF NOT EXISTS contract_assets_asset_idx ON contract_assets(asset_id);
CREATE INDEX IF NOT EXISTS ticket_assets_asset_idx ON ticket_assets(asset_id);
CREATE INDEX IF NOT EXISTS entries_entity_idx ON entries(entity_kind,entity_id,created_at DESC);
CREATE INDEX IF NOT EXISTS notifications_source_idx ON notifications(source_kind,source_id);
