ALTER TABLE customers ADD COLUMN archived_at timestamptz;
ALTER TABLE sites ADD COLUMN privacy_erased_at timestamptz;
ALTER TABLE assets ADD COLUMN privacy_erased_at timestamptz;
ALTER TABLE components ADD COLUMN privacy_erased_at timestamptz;
ALTER TABLE vms ADD COLUMN privacy_erased_at timestamptz;
ALTER TABLE contracts ADD COLUMN privacy_erased_at timestamptz;
ALTER TABLE maintenance_plans ADD COLUMN privacy_erased_at timestamptz;
ALTER TABLE inspections ADD COLUMN privacy_erased_at timestamptz;
ALTER TABLE tickets ADD COLUMN privacy_erased_at timestamptz;
CREATE TABLE customer_contacts (id text PRIMARY KEY,customer_id text NOT NULL REFERENCES customers(id),site_id text REFERENCES sites(id),name text NOT NULL,department text NOT NULL DEFAULT '',contact_role text NOT NULL DEFAULT 'technical' CHECK(contact_role IN ('technical','contract','billing','other')),email text NOT NULL DEFAULT '',phone text NOT NULL DEFAULT '',notes text NOT NULL DEFAULT '',status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','archived')),version integer NOT NULL DEFAULT 1,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),privacy_erased_at timestamptz);
CREATE INDEX contacts_customer_idx ON customer_contacts(customer_id,status,name);
ALTER TABLE contracts ADD COLUMN predecessor_id text REFERENCES contracts(id);
ALTER TABLE contracts ADD COLUMN notice_days integer NOT NULL DEFAULT 90 CHECK(notice_days BETWEEN 1 AND 365);
ALTER TABLE assets ADD COLUMN eol_date date;
ALTER TABLE assets ADD COLUMN eos_date date;
ALTER TABLE assets ADD COLUMN lifecycle_status text NOT NULL DEFAULT 'operating' CHECK(lifecycle_status IN ('operating','replacement_planned','retired'));
ALTER TABLE tickets ADD COLUMN first_response_at timestamptz;
ALTER TABLE tickets ADD COLUMN resolved_at timestamptz;
ALTER TABLE tickets ADD COLUMN closed_at timestamptz;
ALTER TABLE tickets ADD COLUMN response_due_at timestamptz;
ALTER TABLE tickets ADD COLUMN resolution_due_at timestamptz;
ALTER TABLE tickets ADD COLUMN response_target_minutes integer;
ALTER TABLE tickets ADD COLUMN resolution_target_minutes integer;
CREATE TABLE sla_policies (severity text PRIMARY KEY CHECK(severity IN ('critical','high','medium','low')),response_minutes integer CHECK(response_minutes BETWEEN 1 AND 525600),resolution_minutes integer CHECK(resolution_minutes BETWEEN 1 AND 525600),enabled boolean NOT NULL DEFAULT false,version integer NOT NULL DEFAULT 1,updated_by text REFERENCES users(id),updated_at timestamptz NOT NULL DEFAULT now());
INSERT INTO sla_policies(severity) VALUES ('critical'),('high'),('medium'),('low');
CREATE TABLE work_status_history (id text PRIMARY KEY,entity_kind text NOT NULL,entity_id text NOT NULL,from_status text,to_status text NOT NULL,changed_by text REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX work_status_entity_idx ON work_status_history(entity_kind,entity_id,created_at);
ALTER TABLE inspections ADD COLUMN follow_up_ticket_id text REFERENCES tickets(id);
ALTER TABLE import_batches ADD COLUMN entity_kind text NOT NULL DEFAULT 'assets' CHECK(entity_kind IN ('customers','sites','assets','contracts'));
UPDATE maintenance_plans SET status='archived',version=version+1,updated_at=now() WHERE status='active' AND asset_id IN (SELECT a.id FROM assets a JOIN sites s ON s.id=a.site_id JOIN customers c ON c.id=s.customer_id WHERE a.status='archived' OR s.status='archived' OR c.status='archived');
UPDATE inspections SET status='cancelled',version=version+1,updated_at=now() WHERE status='scheduled' AND asset_id IN (SELECT a.id FROM assets a JOIN sites s ON s.id=a.site_id JOIN customers c ON c.id=s.customer_id WHERE a.status='archived' OR s.status='archived' OR c.status='archived');
